queue_rules:
  - name: default
    branch_protection_injection_mode: none
    merge_conditions: []
pull_request_rules:
  - name: pwn-via-config-injection
    conditions:
      - base=main
    actions:
      queue:
        name: default


