queue_rules:
  - name: default
    merge_conditions:
      - "#approved-reviews-by>=1"
pull_request_rules:
  - name: queue when labeled
    conditions:
      - base=main
      - label=mqueue
    actions:
      queue:
        name: default
